### ISSUE TITLE
baseline setup reference

### ISSUE THREAD

**Issue by gmkim90** [dialogtekgeek/DSTC6-End-to-End-Conversation-Modeling#2]
Hello.
First of all, thanks for the challenge organizer's hard effort.
Could you share any reference for baseline system in twitter/opensubtitle?

**Comment by takaaki-hori** [comment]
Hi, are you mentioning about the data sets or the technical inside of the system?

**Comment by gmkim90** [comment]
I was talking about "technical inside" such as which algorithm or paper it refers to.

**Comment by takaaki-hori** [comment]
The baseline system follows Vinyals' paper: https://arxiv.org/pdf/1506.05869.pdf
One difference from the paper would be that back-propagation is done only up to the previous sentence from the current sentence, although the state information is taken over throughout the dialog.
This reduces computation and memory usage but may be not so good for training long context dependency.

**Comment by gmkim90** [comment]
Thanks for the clarification :+1:
